### ISSUE TITLE
Drugi projektni sastanak

### ISSUE THREAD

**Issue by gornjas** [dlfpga/2015#1]
Studente koji su zapoceli s izradom projekata i zele ih nastaviti molim da odgovore na ovu poruku, kako bi mogli pronaci termin sastanka (krajem ovog tjedna) koji ne bi kolidirao s drugim nastavnim obavezama. Na sastanku bi svaki student trebao kratko predstaviti konkretne korake koje je do sad uspio ostvariti, i time bi nadomjestio odradu 5. lab. vjezbe. Zavrsetak projekata treba planirati okvirno do nedjelje 23. sijecnja.

Za studente koji ne odgovore na ovu poruku smatrat cemo da odustaju od izrade projekata i da ce nastaviti s redovnom odradom laboratorijskih vjezbi, sto su neki vec najavili.

Ujedno se svima koji su me pokusali kontaktirati elektronickom postom ispricavam zbog sporog odgovora, buduci da sam koristio godisnji odmor.

**Comment by fjaka** [comment]
Nastavljam

Antonio Matušan
0036490268

**Comment by BojanoN** [comment]
Nastavljam

Bojan Novković
0036491382

**Comment by chillipi** [comment]
Nastavljam

Ivan Ilić
0036491585

**Comment by Vidyapoky** [comment]
Nastavljam

Matija Roglić
0036491057

**Comment by JDMKing** [comment]
Nastavljam

Vladimir Radoš
0036494566

**Comment by MasterMedo** [comment]
Nastavljam

Mislav Vuletić
0036490616

**Comment by gornjas** [comment]
Predlazem sastanak u ponedjeljak, 18. 1. u 17:30, postrojavanje ispred Zavoda za telekomunikacije, 7. kat zgrade C.
Molim uz razvojne plocice ponesite i vlastita prijenosna racunala buduci da budemo vjerojatno bili u dvorani bez stolnih racunala s instaliranim razvojnim alatima za Lattice FPGA.
